### ISSUE TITLE
Inline view closing force quits the app

### ISSUE THREAD

**Issue by BennoCrafter** [project-gauntlet/gauntlet#70]
When e.g. trying to copy result from calculator it force quits gauntlet. Probably because of my changes made for fixing window state

**Comment by Exidex** [comment]
v19 with fix has been released

**Comment by BennoCrafter** [comment]
it still doesn't work 

https://github.com/user-attachments/assets/dd96dfd2-b588-4798-8d50-4221fd9dbbc7

**Comment by Exidex** [comment]
It seems fix only works on linux, macos is still broken.

**Comment by Mrid22** [comment]
> It seems fix only works on linux, macos is still broken.

can confirm, I am on nix os, and the issue still exists.
